### ISSUE TITLE
ERROR in The target entry-point "ngx-swiper-wrapper" has missing dependencies

### ISSUE THREAD

**Issue by Dolgovec** [zefoy/ngx-swiper-wrapper#282]
Not working with the latest angular version (10.1.2)

Representation:
- Create new angular project via `ng new test-app`
- Follow your `README `guide and install `ngx-swiper-wrapper`
- Try to serve via `ng serve`

Result: You will get error with the following text:
```
ERROR in The target entry-point "ngx-swiper-wrapper" has missing dependencies:
 - swiper/bundle
 - swiper
 - swiper/types/swiper-events
```

**Comment by sharathdaniel** [comment]
Same issue here

**Comment by sconix** [comment]
It seems that the package json is missing swiper dependency, will add it to next release. Until that you can just install swiper package manually.

**Comment by Dolgovec** [comment]
Yea, `npm install swiper --save-dev` resolves the problem. Thank you

**Comment by AlirezaPhf** [comment]
Same issue here
how to import manual swiper dependencies ?

**Comment by developermw-4** [comment]
Same issue here but  installing
 "ngx-swiper-wrapper": "5.2.1"  resolves .

**Comment by Art2058** [comment]
same issue

"ngx-swiper-wrapper": "^10.0.0"

**Comment by matthiasunt** [comment]
Same issue after updating to Angular 10.
`"ngx-swiper-wrapper": "^10.0.0"`

**Comment by yukondesu** [comment]
Same issue after updating to Angular 10.2.0
"ngx-swiper-wrapper": "^10.0.0"

**Comment by webcat12345** [comment]
@sconix Could you please let me know if `swiper` is a normal dependency or dev dependency?

**Comment by csimpi** [comment]
confirmed after updating to 10.0.0, `npm install swiper --save-dev` helped

**Comment by Nilena** [comment]
i got the same issue and solved with npm install swiper --save-dev

**Comment by thabangco** [comment]
I had a similar issue, I solved it by running `npm install swiper --save-dev`

**Comment by pavandixit93** [comment]
> It seems that the package json is missing swiper dependency, will add it to next release. Until that you can just install swiper package manually.

Hi @sconix Any update on this, eagerly waiting to get fixed. meanwhile using given workaround, `npm install swiper --save-dev`

**Comment by Lessnic** [comment]
Still not fixed.

**Comment by sconix** [comment]
This has been fixed a long time ago. Swiper is include in the peer dependencies.

**Comment by taychris** [comment]
Just tried to set it up, still not fixed.

**Comment by lioragami1** [comment]
Having the same issue as @reinaldoborin .

**Comment by Rayen-cherni** [comment]
still a have an issue !
swiper/bundle !

**Comment by unityvirgins** [comment]
I also still have an issue after updating to angular 12 and did **npm install swiper --save-dev**

Error: The target entry-point "ngx-swiper-wrapper" has missing dependencies:
 - swiper/bundle

**Comment by suarezana9** [comment]
My problem continued after installing ** npm install swiper --save-dev **, so I decided to install a specific version ** npm i swiper@6.4.15 and it was solved.

**Comment by renis1235** [comment]
The solution from @suarezana9 solved my problem.

Installing another version of swiper did the job.

**Comment by SimonPrimetzhofer** [comment]
> The solution from @suarezana9 solved my problem.
> 
> Installing another version of swiper did the job.

yes, same for me. it seems that it breaks with version >= 7

**Comment by mikelhamer** [comment]
Reverting to version 9 fixed this for me

**Comment by dsebata** [comment]
> **_Solved_**
> 
> * `npm uninstall ngx-swiper-wrapper`
> * **Install** ` npm i swiper`
> * For import use `import { SwiperModule } from 'ngx-swiper-wrapper';`  instead of `import { SwiperModule } from 'swiper/angular';`

Thanks @sweetnandha.
Had to also...

- Replace all `<div [swiper]="config">` with `<div swiper [config]=config>`
- Replace all `SwiperConfigInterface` with `SwiperOptions`
- Change  `<div *ngFor="let slide of slides" class="swiper-slide">` to `<ng-template swiperSlide *ngFor="let slide of slides"> <div class="swiper-slide"> ... </div> </ng-template>`
- add to app.module. Be sure to add all modules 
   ```
    import SwiperCore, {Lazy, Navigation, Pagination} from 'swiper';
    SwiperCore.use([Navigation, Pagination, Lazy]);
   ```
- import swiper styles

[Swiper Angular doc](https://swiperjs.com/angular)

**Comment by webnetweaver** [comment]
I can't get this integrated.  @dsebata where do you import SwiperOptions from?  That is not exported from swiper/angular.  I keep running into errors or missing symbols.  Why is this so impossible to install?

**Comment by dsebata** [comment]
import { SwiperOptions, SwiperEvents, NavigationOptions,
PaginationOptions, ScrollbarOptions, VirtualOptions } from
'swiper/types';

**Comment by gabriel216** [comment]
> My problem continued after installing **npm install swiper --save-dev** , so I decided to install a specific version **npm i swiper@6.4.15** and it was solved.

Thank you! it works

**Comment by Prateek-Mishra1009** [comment]
> 

need a help i also getting same issue with swiper 10.0.0
